name: Effect on GitHub

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/effect-ci.yml
    with:
      workflow: .cloudflare/ci/workflow.ts
      runs-on: ${{ vars.EFFECT_CI_RUNS_ON || '["ubuntu-latest"]' }}
