import { mkdir, readFile, writeFile } from "node:fs/promises"

const source = await readFile(new URL("../src/message.js", import.meta.url), "utf8")

await mkdir(new URL("../dist", import.meta.url), { recursive: true })
await writeFile(
  new URL("../dist/index.js", import.meta.url),
  `// generated by the cached Turborepo task\n${source}`,
)

console.log("built @turborepo-cache/message")
