name: GitHub Actions

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          package-manager-cache: false
      - run: cd apps/backend && npx cf build --mode production
      - run: cd apps/frontend && npx cf build --mode production
      - run: cd apps/backend && npx cf deploy --prebuilt --mode production --dry-run
      - run: cd apps/frontend && npx cf deploy --prebuilt --mode production --dry-run
