name: GitHub Actions

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  imagemagick:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: sudo apt-get update
      - run: sudo apt-get install --yes --no-install-recommends imagemagick
      - run: convert -version | grep --fixed-strings ImageMagick
