name: GitHub Actions

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v3
        with:
          runtime: node@24
          cache: true
          require-lockfile: true
      - parallel:
          - run: pnpm run lint
          - run: pnpm run format
            continue-on-error: true
      - run: pnpm test
      - run: pnpm run build
      - run: echo pnpx cf deploy
