name: Effect CI on GitHub

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/effect-ci.yml
    with:
      cache-key: turbo-task
      cache-key-files: app/package-lock.json
      cache-path: app/.turbo/cache
      workflow: .cloudflare/ci/workflow.ts
    secrets: inherit
