name: Effect on GitHub

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/effect-ci.yml
    with:
      cache-key: node-version
      cache-key-files: .node-version
      cache-path: .effect-ci/cache/mise
      workflow: .cloudflare/ci/workflow.ts
