name: GitHub Actions

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          package-manager-cache: false
      - run: npm exec --yes --package=prettier@3.6.2 -- prettier --check app/src/index.ts --no-semi
