import { WorkflowEntrypoint, type WorkflowEvent, type WorkflowStep } from "cloudflare:workers"
import { reconcileTelemetry } from "../../../packages/cloudflare/src/telemetry-cohort.ts"
import { sqlFetchOutcome } from "./wobs-cohort.ts"

const BASELINE = "09593237-23b2-4873-bd04-88c8e8488840"
const ONCE = { retries: { limit: 0, delay: "1 second" } } as const

/** Authenticated, bounded read-only deployment lab. No broker mutations, credentials,
 * repository code, ambient traffic claims or notifications. SQL availability is
 * account-observed experimental behavior, not yet a documented binding contract.
 */
export class WobsCohortProbeWorkflow extends WorkflowEntrypoint<{ ANALYTICS_SQL: AnalyticsSQLBinding }> {
  override async run(_event: Readonly<WorkflowEvent<unknown>>, step: WorkflowStep) {
    const manifest = await step.do("wobs:expected-identities", ONCE, async () => {
      return { version: BASELINE, from: Date.now(), expected: 20 }
    })
    const traffic = await step.do("wobs:bounded-traffic", ONCE, async () => {
      let acknowledged = 0
      let unknown = 0
      const rays: string[] = []
      for (let index = 0; index < manifest.expected; index += 5) {
        await Promise.all(Array.from({ length: 5 }, async () => {
          try {
            const response = await fetch("https://effect-ci-hmd-demo.ericclemmons.workers.dev/health", { redirect: "manual", signal: AbortSignal.timeout(10_000), headers: { "cache-control": "no-cache" } })
            const body = await response.json() as { version?: string; healthy?: boolean }
            if (body.version !== BASELINE || response.status !== 200 || body.healthy !== true) throw new Error("Unexpected baseline")
            const ray = response.headers.get("cf-ray")?.split("-")[0]
            if (!ray || !/^[a-f0-9]{16}$/.test(ray)) throw new Error("Missing native receipt")
            rays.push(ray)
            acknowledged++
          } catch { unknown++ }
        }))
      }
      return { acknowledged, unknown, rays }
    })
    const to = await step.do("wobs:close-expected-window", ONCE, async () => Date.now() + 1)
    // CF-Ray receipts are generated by the edge and captured independently BEFORE
    // reading SQL. Query parameters remain redacted; no logging privacy is relaxed.
    if (traffic.unknown || traffic.rays.length !== 20 || new Set(traffic.rays).size !== 20) return {
      complete: false, traffic, observations: [], scope: "incomplete independent native receipts" }
    const observations = []
    for (let attempt = 0; attempt < 6; attempt++) {
      // Query time is never an ingest watermark. Only all expected identities close.
      const observation = await step.do(`wobs:reconcile-${attempt}`, ONCE, async () => {
        const result = await this.env.ANALYTICS_SQL.query({
          query: `SELECT timestamp, scriptName, logType, requestId, rayId, sampleInterval, attributes FROM logs.workersLogs WHERE scriptName = $script AND timestamp >= $from AND timestamp < $to AND rayId IN (${traffic.rays.map((_, index) => `$ray${index}`).join(",")}) LIMIT 100`,
          params: { script: "effect-ci-hmd-demo", from: new Date(manifest.from).toISOString(), to: new Date(to).toISOString(),
            ...Object.fromEntries(traffic.rays.map((ray, index) => [`ray${index}`, ray])) },
        })
        const native = result.data.filter((row) => row.logType === "cf-worker-event")
        const reconciled = reconcileTelemetry({ version: manifest.version, from: manifest.from, to, ids: traffic.rays }, native.map(sqlFetchOutcome))
        return { ...reconciled, logTypes: [...new Set(result.data.map((row) => row.logType))].filter((v): v is string => typeof v === "string" && /^[a-zA-Z_-]{1,32}$/.test(v)),
          rawRows: result.rows, nativeRows: native.length, observedAt: Date.now() }
      })
      observations.push(observation)
      if (observation.sample.completeThrough === to) return { complete: true, traffic, observations,
        scope: "twenty closed synthetic baseline requests, not ambient traffic or a release gate" }
      if (attempt < 5) await step.sleep(`wobs:ingestion-wait-${attempt}`, "30 seconds")
    }
    return { complete: false, traffic, observations, scope: "missing/invalid native evidence remains uncertain" }
  }
}
