name: examples/node-npm/.github/workflows/effect-on-github.yml

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/effect-ci.yml
    with:
      workflow: examples/node-npm/ci.run.ts
