name: node-npm / effect-on-github

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  effect-on-github:
    uses: ./.github/workflows/effect-ci.yml
    with:
      workflow: examples/node-npm/ci.run.ts
